- name: Install add-apt-repostory
  become: True
  become_method: "sudo"
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: True
  become_method: "sudo"
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: True
  become_method: "sudo"
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: True
  become_method: "sudo"
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
