- name: Download ElasticSearch package
  get_url: url=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb dest=/tmp/elasticsearch-5.1.1.deb

- name: Install ElasticSearch
  become: True
  become_method: "sudo"
  shell: dpkg -i /tmp/elasticsearch-5.1.1.deb

- name: copy settings to /etc/elasticsearch/elasticsearch.yml
  become: True
  become_method: "sudo"
  copy: src=./files/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml

- name: copy jvm.options to /etc/elasticsearch
  become: True
  become_method: "sudo"
  copy: src=./files/jvm.options dest=/etc/elasticsearch/jvm.options

- name: reload systemctl
  become: True
  become_method: "sudo"
  command: systemctl daemon-reload

- name: make sure ElasticSearch is enabled
  become: True
  become_method: "sudo"
  service: name=elasticsearch.service enabled=yes

- name: make sure ElasticSearch is restarted
  become: True
  become_method: "sudo"
  service: name=elasticsearch.service state=restarted

- name: waiting for ElasticSearch
  wait_for:
    port: 9200
    delay: 5

- name: copy elasticsearch_indices.sh (can not use python3 yet for uri module)
  copy: src=./files/elasticsearch_indices.sh dest=/tmp/elasticsearch_indices.sh

- name: copy tweets_index.json
  copy: src=./files/tweets_index.json dest=/tmp/tweets_index.json

- name: copy tweet_mapping.json
  copy: src=./files/tweet_mapping.json dest=/tmp/tweet_mapping.json

- name: create ElasticSearch indices
  command: /bin/sh /tmp/elasticsearch_indices.sh
