- name: copy package.json
  copy: src=../data-stream/package.json dest=/home/ubuntu/

- name: copy index.js
  copy: src=../data-stream/index.js dest=/home/ubuntu/

- name: copy settings.json
  copy: src=../data-stream/settings.json dest=/home/ubuntu/

- name: copy .env
  copy: src=../data-stream/.env dest=/home/ubuntu/

- name: install node modules
  command: npm install

- name: copy data_stream.service
  become: True
  become_method: "sudo"
  copy: src=./files/data_stream.service dest=/etc/systemd/system/data_stream.service

- name: reload systemctl
  become: True
  become_method: "sudo"
  command: systemctl daemon-reload

- name: enable data_stream.service
  become: True
  become_method: "sudo"
  service: name=data_stream.service enabled=yes

- name: restart data_stream.service
  become: True
  become_method: "sudo"
  service: name=data_stream.service state=restarted
