- name: copy package.json
  become: True
  become_method: "sudo"
  copy: src=../api/package.json dest=/opt/api/

- name: copy index.js
  become: True
  become_method: "sudo"
  copy: src=../api/index.js dest=/opt/api/

- name: install node modules
  become: True
  become_method: "sudo"
  command: npm install --prefix /opt/api

- name: copy api.service
  become: True
  become_method: "sudo"
  copy: src=./files/api.service dest=/etc/systemd/system/api.service

- name: reload systemctl
  become: True
  become_method: "sudo"
  command: systemctl daemon-reload

- name: enable api.service
  become: True
  become_method: "sudo"
  service: name=api.service enabled=yes

- name: restart api.service
  become: True
  become_method: "sudo"
  service: name=api.service state=restarted
